name: 'Export Gerbers'
description: 'Export Gerber files from a Kicad PCB'
inputs:
  pcb_file:
    description: 'Kicad input file'
    required: true
  gerbers_dir:
    description: 'Gerbers folder'
    required: true
  fab:
    description: 'Fabrication profile'
    default: 'jlcpcb'
  flags:
    description: 'Additional flags for kikit fab'
    default: '--no-assembly --no-drc'
  draw:
    description: 'PCBDraw options'
    default: 'plot --dpi 800 --filter "" --style builtin:jlcpcb-green-enig.json'
runs:
  using: 'docker'
  image: 'docker://yaqwsx/kikit:nightly'
  entrypoint: '/bin/sh'
  args:
    - '-c'
    - |
      mkdir -p $GITHUB_WORKSPACE/${{ inputs.gerbers_dir }} ;
      kikit fab ${{ inputs.fab }} ${{ inputs.flags }} $GITHUB_WORKSPACE/${{ inputs.pcb_file }} $GITHUB_WORKSPACE/${{ inputs.gerbers_dir }} ;
      pcbdraw ${{ inputs.draw }} $GITHUB_WORKSPACE/${{ inputs.pcb_file }} $GITHUB_WORKSPACE/${{ inputs.gerbers_dir }}/front.png ;
      pcbdraw ${{ inputs.draw }} --side back $GITHUB_WORKSPACE/${{ inputs.pcb_file }} $GITHUB_WORKSPACE/${{ inputs.gerbers_dir }}/back.png ;
#     kikit present boardpage gerbers --description $GITHUB_WORKSPACE/README.md --board "" "" $GITHUB_WORKSPACE/${{ inputs.pcb_file }} --name myname
