on: [push, pull_request, workflow_dispatch]

name: Build
jobs:
  generate:
    runs-on: ubuntu-latest
    name: Generate
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Export Gerbers
        uses: ./.github/actions/export-gerbers
        with:
          pcb_file: hardware/nrfmicro.kicad_pcb
          gerbers_dir: gerbers

      - name: Persist output
        uses: actions/upload-artifact@v2
        with:
          name: nrfmicro-gerbers
          path: gerbers

      - name: Gets latest created release info
        id: latest_release_info
        uses: jossef/action-latest-release-info@v1.1.0
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Upload release binary
        uses: actions/upload-release-asset@v1.0.2
        with:
          upload_url: ${{ steps.latest_release_info.outputs.upload_url }}
          asset_path: ./gerbers/nrfmicro-front.png
          asset_name: nrfmicro-front.png
          asset_content_type: image/png
