on: [push, pull_request, workflow_dispatch]

name: Build
jobs:
  generate:
    runs-on: ubuntu-latest
    name: Generate
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Export Gerbers
        uses: ./.github/actions/export-gerbers
        with:
          pcb_file: hardware/nrfmicro.kicad_pcb
          gerbers_dir: gerbers

      - name: Persist output
        uses: actions/upload-artifact@v2
        with:
          name: nrfmicro-gerbers
          path: gerbers

      - name: Get upload URL
        id: geturl
        run:   |
               upload_url=$(curl -sL https://api.github.com/repos/actions/checkout/releases/latest | jq -r '.upload_url')
               echo UPLOAD_URL=$upload_url >> $GITHUB_ENV
        shell: bash

      - name: Upload Release Asset
        id: upload-release-asset
        uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{ env.UPLOAD_URL }}
          asset_path: $GITHUB_WORKSPACE/gerbers/nrfmicro-front.png
          overwrite: true
